import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/header'
import SideBarPage from '@/components/sidebar/page'
import Providers from './providers'
import { AuthProvider } from './AuthProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log('in LAYOUT')
  return (
    <html lang="en">
      <body>

        <div>
        <AuthProvider>
          <Header />
          <div className='flex flex-row'>
            <div className='basis-1/5'>
              <SideBarPage/>
            </div>
            <div className='basis-4/5'>
              <Providers>{children}</Providers>
            </div>
          </div>
          </AuthProvider>
        </div>
      </body>
    </html>
  )
}
