import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/header'
import SideBar from '@/components/sidebar'
import Providers from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <Header />
          <div className='flex flex-row'>
            <div className='basis-1/5'>
              <SideBar />
            </div>
            <div className='basis-4/5'>
              <Providers>{children}</Providers>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
